###############################################################################
#   @author         :   Richard Jenkins 
#   @date           :   23/08/20
#   @subject        :   Z4 BMW Integration 
#   @description    :   BMW Automations 
#   @version        :   1.7
#   @Comment        :   
###############################################################################
# homeassistant:
#   customize:

##############################  AUTOMATION ####################################
# binary_sensor.z4_sdrive20i_door_lock_state
# on = unlocked 
# off = locked
automation:
  - id: Z4C.001
    alias: Z4 arrive home and not locked
    trigger:
      - platform: state
        entity_id: device_tracker.z4_sdrive20i
        to: 'home'
        for:
          minutes: 20
    condition:
      - condition: state
        entity_id: binary_sensor.z4_sdrive20i_door_lock_state
        state: 'on'
    action: 
      - service: homeassistant.turn_on
        entity_id: lock.z4_sdrive20i_lock
      - delay: 3
      - service: sonos.snapshot
        entity_id: media_player.living_room_sonos
      - service: tts.cloud_say
        data:
          entity_id: media_player.living_room_sonos
          message: 'The Z4 has been locked'
          options:
            gender: female
          language: en-GB
      - delay: 3
      - service: sonos.restore
        entity_id: media_player.living_room_sonos

  - id: Z4C.002
    alias: Z4 unlocked at home and not relocked
    trigger:
      - platform: state
        entity_id: binary_sensor.z4_sdrive20i_door_lock_state
        to: 'on'
        for: 
          minutes: 10
    condition: 
      - condition: state
        entity_id: device_tracker.z4_sdrive20i
        state: 'home'   
    action: 
      - service: homeassistant.turn_off
        entity_id: lock.z4_sdrive20i_lock
      - delay: 3
      - service: sonos.snapshot
        entity_id: media_player.living_room_sonos
      - service: tts.cloud_say
        data:
          entity_id: media_player.living_room_sonos
          message: 'The Z4 has been unlocked for 5 minutes'
          options:
            gender: female
          language: en-GB
      - delay: 3
      - service: sonos.restore
        entity_id: media_player.living_room_sonos
      
      
        
  

##############################  INPUT BOOLEAN ################################

input_boolean:
# none


##############################  SCRIPTS ########################################
# script:
  # car_check:
  #   sequence: 
  #     choose:
  #       - conditions:
  #           - condition: state
  #             entity_id: z4_sdrive20i_door_lock_state
  #             state: 'off'
  #         sequence:
  #             - service: input_boolean.turn_on
  #               entity_id: input_boolean.guard_mode # set guard mode if doors and windows closed
  #       - conditions:
  #           - condition: state
  #             entity_id: group.opening
  #             state: 'on'
  #         sequence:
  #             - service: input_boolean.turn_on
  #               entity_id: input_boolean.security_issue # set security issue if doors or windows open
  #             - service: script.sonos_say
  #               data:
  #                 sonos_entity: media_player.living_room_sonos
  #                 volume: 0.5
  #                 message: 'Attention, a door or window is open, the alarm could not arm'
  #                 delay: '00:02:05'

##############################  SCENES ########################################
# scenes:
# none

#############################  GROUPS ########################################
# group:
# none

#############################  END ############################################
